check50:
  checks:
    hw01:
      - run: python hw01.py
        stdout: Hello, Python world!
        exit: 0
    hw02 1:
      - run: python hw02.py
        stdin: 1 2
        stdout: 3
        stdin: 4 5
        stdout: 9
        stdin: 2 6
        stdout: 8
        exit: 0
