check50:
  checks:
    w01-hw01 basic check:
      - run: python hw01.py
        stdout: Hello Python World!
        exit: 0
    w01-hw02 basic check:
      - run: python hw02.py
        stdin: 1 2
        stdout: 1 2 3
        exit: 0
    w01-hw02 advanced check:
      - run: python hw02.py
        stdin: 
            - 1 2
            - 1 2 3
            - 1 2 3 4
        stdout: 
            - 1 2 3
            - 6
            - 1 2 3 4 10
        exit: 0
