check5:
  checks:
    w01-hw01 basic check:
      - run: python hw01.py
        stdout: Hello Python World!
        exit: 0
    w01-hw02 1 test case:
      - run: python hw02.py
        stdin: 1 2
        stdout: 1 2 3
        exit: 0
    w01-hw02 3 test cases:
      - run: python hw02.py
        stdin: 1 2
        stdout: 1 2 3
        stdin: 1 2 3
        stdout: 6
        stdin: 1 2 3 4
        stdout: 1 2 3 4 10
        exit: 0
