check50:
  checks:
    hw01:
     - run: python3 hw01.py 
        stdout: Hello, Python world!
        exit: 0
    hw02:
      - run: python3 hw02.py 
        stdin: 1 3
        stdout: 4
        exit: 0 
