check50: True
  checks:
    w02-hw01:
      - run: python hw01.py
        stdin: 2
        stdout: |
          *
          **
        stdin: 4
        stdout: |
          *
          **
          ***
          ****
        exit: 0
