check50:
  checks:
    test01:
      - run: python3 main.py
        stdin: '22 33'
        stdout: 55
        exit: 0
    test02:
      - run: python3 main.py
        stdin: '11 22 33'
        stdout: 66
        exit: 0
    test03:
      - run: python3 main.py
        stdin: '1 2 3 4 5 6 7 8 9 10'
        stdout: 55
        exit: 0

